In [2]:
import numpy as np

def compute_vector_length(vector):
    return np.linalg.norm(vector)

vector = np.array([1,2,3])

result = compute_vector_length(vector)
result


3.7416573867739413

In [3]:
def compute_dot_product(vector1, vector2):
    return np.dot(vector1, vector2)

vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

result = compute_dot_product(vector1, vector2)
result


32

In [5]:

def matrix_multi_vector(vector1, vector2):
    return np.dot(vector1, vector2)

vector1 = np.array([1,2,3])
vector2 = np.array([[4,5,6],
                   [7,8,9],
                   [10,11,12]])

result = matrix_multi_vector(vector1, vector2)
result


array([48, 54, 60])

In [7]:
def matrix_multi_matrix(matrix1, matrix2):
    return np.matmul(matrix1, matrix2)

matrix1 = np.array([1,2,3])
matrix2 = np.array([[4,5,6],
                   [7,8,9],
                   [10,11,12]])

result = matrix_multi_matrix(matrix1, matrix2)
result

array([48, 54, 60])

In [8]:
def matrix_inverse(matrix):
    return np.invert(matrix)

matrix = np.array([[4,5,6],
                   [7,8,9],
                   [10,11,12]])
result = matrix_inverse(matrix)
result


array([[ -5,  -6,  -7],
       [ -8,  -9, -10],
       [-11, -12, -13]])

In [4]:
def eig(matrix):
    return np.linalg.eig(matrix)

matrix = np.array([[4,5,6],
                   [7,8,9],
                   [10,11,12]])
lambdas, V = eig(matrix)
lambdas

array([ 2.47279221e+01, -7.27922061e-01,  1.46904603e-15])

In [5]:
V

array([[-0.35200306, -0.76057531,  0.40824829],
       [-0.55343002, -0.05691242, -0.81649658],
       [-0.75485698,  0.64675048,  0.40824829]])

In [4]:
def cosine_similarity(x, y):
    return np.dot(x, y) / (np.linalg.norm(x)*np.linalg.norm(y))

x = np.array([4, 2, 1, 2])
y = np.array([1, 2, 2, 0])


result = cosine_similarity(x, y)
result

0.6666666666666666