In [1]:
import numpy as np

arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr = np.ones((3,3)) > 0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.ones((3,3) , dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
arr = np.full((3,3), fill_value=True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [6]:
arr = np.arange(0,10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [7]:
arr = np.arange(0,10)
print(arr[arr%2 == 1])
arr[arr%2 == 1] = -1
print(arr)

[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([arr1, arr2], axis = 0)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate([arr1, arr2], axis = 1)
print("Result: \n", c)

Result: 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [11]:
arr = np.array([1,2,3])
print(arr.repeat(3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [12]:
arr = np.array([2,6,1,9,10,3,27])
index = np.where((arr>=5) & (arr<=10))
print(arr[index])


[ 6  9 10]


In [13]:
import math
def maxx(x,y):
    return max(x,y)

a = np.array([5,7,9,5,6,4,5])
b = np.array([6,3,4,8,7,9,1])

max_pair = np.vectorize(maxx, otypes=[float])

print(max_pair(a,b))

[6. 7. 9. 8. 7. 9. 5.]


In [14]:
a = np.array([5,7,9,5,6,4,5])
b = np.array([6,3,4,5,9,7,1])

print(np.where(a<b, b, a))
print(np.where(a<b, a, b))

[6 7 9 5 9 7 5]
[5 3 4 5 6 4 1]
